name: Build

on:
    push:
        branches:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: '16.x'

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm build

            - name: Generate buildnumber
              run: |
                  date -u '+%Y-%m-%d %H:%M:%S' > dist/dev-tools/buildinfo.txt
                  echo $BUILD_NUMBER >> dist/dev-tools/buildinfo.txt
                  echo $GIT_COMMIT >> dist/dev-tools/buildinfo.txt
